name: bluevoice
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  system_shortcuts: 1.0.0
  flui: 0.9.2
  shared_preferences: 2.0.7
  intl: 0.17.0
  android_intent_plus: 2.0.0
  flutter_blue: 0.8.0
  platform: 3.0.2
  path_provider:  ^1.0.0
  path: 1.8.0
  # sqflite: 2.0.0+4
  # dbutils: 4.0.1
  flutter_slidable: 0.6.0
  flutter_sound: ^4.0.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

